apiVersion: v1
kind: Pod
metadata:
  name: echo
  namespace: default
  labels:
    name: echo
spec:
  containers:
  - image: busybox
    name: test-hello
    command: ['sh', '-c', 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 0.01; done']
  
