# @brief Storageclass
# @author mhw
# @date 2018-05-15 
#

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd				
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.129.4.54:6789		
  adminId: admin
  adminSecretName: ceph-secret		
  adminSecretNamespace: kube-system
  pool: rbd
  userId: admin
  userSecretName: ceph-secret
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
