---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-http-backend-echo
  labels:
    app: default-http-backend-echo
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-http-backend-echo
  template:
    metadata:
      labels:
        app: default-http-backend-echo
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend-echo
        # Any image is permissible as long as:
        # 1. It serves a 404 page at /
        # 2. It serves 200 on a /healthz endpoint
        image: kitematic/hello-world-nginx
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
---

apiVersion: v1
kind: Service
metadata:
  name: default-http-backend-echo
  namespace: ingress-nginx
  labels:
    app: default-http-backend-echo
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: default-http-backend-echo
